-- Los Turquitos — catálogo de productos en Supabase (mismo proyecto que `leads`)
-- Correr en el SQL Editor del proyecto.

create table if not exists productos (
  id bigint generated by default as identity primary key,
  categoria_id text not null,
  categoria_label text not null,
  nombre text not null,
  unidad text not null,
  precio int not null,
  activo boolean not null default true
);

-- El catálogo lo ve cualquier cliente sin necesidad de loguearse,
-- por eso acá la lectura es pública (a diferencia de `leads`, que exige login).
alter table productos enable row level security;

drop policy if exists "Cualquiera puede ver productos activos" on productos;
create policy "Cualquiera puede ver productos activos"
  on productos for select
  using (activo = true);

-- Sin política de insert/update/delete para el público: los productos se cargan/editan
-- por migrate_productos_to_supabase.py (service_role) o a mano desde el Table Editor.
