-- Los Turquitos — presupuestos del panel de Karim (correr una sola vez en el SQL Editor).
-- Karim arma presupuestos para sus clientes desde el panel (pestaña Presupuestos), los guarda como historial
-- y puede duplicarlos para repetirlos. Solo los ve y edita un usuario logueado (RLS): el público no tiene acceso.
create table if not exists presupuestos (
  id bigint generated by default as identity primary key,
  cliente_nombre text,
  cliente_telefono text,
  nota text,
  items jsonb not null default '[]'::jsonb,   -- [{producto_id, nombre, unidad, precio, cantidad}]
  descuento_pct int not null default 0 check (descuento_pct between 0 and 100),
  total int not null default 0,               -- total final, con el descuento ya aplicado
  estado text not null default 'borrador' check (estado in ('borrador','enviado','aceptado','rechazado')),
  valido_hasta date,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table presupuestos enable row level security;

drop policy if exists "Usuarios logueados administran presupuestos" on presupuestos;
create policy "Usuarios logueados administran presupuestos"
  on presupuestos for all
  to authenticated
  using (true)
  with check (true);
