-- Los Turquitos / Karim — esquema de leads en Supabase
-- Correr una sola vez en el SQL Editor del proyecto.

create table if not exists leads (
  id bigint generated by default as identity primary key,
  empresa text not null,
  tipo_negocio text,
  categoria_producto text,
  ciudad text,
  direccion text,
  telefono text,
  prioridad text,
  score int,
  web_actual text,
  diagnostico text,
  hook_venta text,
  estado text not null default 'nuevo'
    check (estado in ('nuevo','contactado','interesado','cotizado','cliente','descartado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa, telefono, ciudad)
);

-- Actualiza updated_at automáticamente en cada cambio
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_leads_updated_at on leads;
create trigger trg_leads_updated_at
  before update on leads
  for each row execute function set_updated_at();

-- Seguridad: nadie puede leer ni escribir sin estar logueado.
-- El script de Python usa la service_role key (que ignora RLS) para insertar/actualizar leads.
-- El tablero web usa un usuario logueado (Supabase Auth) para leer y mover leads entre estados.
alter table leads enable row level security;

drop policy if exists "Usuarios logueados pueden ver leads" on leads;
create policy "Usuarios logueados pueden ver leads"
  on leads for select
  using (auth.role() = 'authenticated');

drop policy if exists "Usuarios logueados pueden actualizar estado" on leads;
create policy "Usuarios logueados pueden actualizar estado"
  on leads for update
  using (auth.role() = 'authenticated');

-- Sin política de insert/delete para authenticated/anon: solo el script (service_role) carga leads nuevos.
