-- Los Turquitos — pedidos generados desde el catálogo público
create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  cliente_nombre text,
  nota text,
  items jsonb not null,
  total int not null,
  creado_en timestamptz not null default now()
);

alter table pedidos enable row level security;

-- Cualquiera (incluso sin loguearse) puede crear un pedido desde el catálogo público.
drop policy if exists "Cualquiera puede crear un pedido" on pedidos;
create policy "Cualquiera puede crear un pedido"
  on pedidos for insert
  to anon, authenticated
  with check (true);

-- Solo un usuario logueado (Karim) puede ver los pedidos ya creados.
drop policy if exists "Solo usuarios logueados pueden ver pedidos" on pedidos;
create policy "Solo usuarios logueados pueden ver pedidos"
  on pedidos for select
  using (auth.role() = 'authenticated');
